apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    database: "claude-code-logs"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.11.0"
      includeFrozen: false
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
      interval: Daily
      timeInterval: "5s"
    editable: true
